import { Item } from "@/types";

export const WomenClothing: Item[] = [
  {
    category: "women",
    image: "/items/women/black-sweatshirt.jpg",
    name: "Black Sweatshirt",
    brand: "Jhvani's Brand",
    price: 123,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/white-tshirt.jpg",
    name: "White T-Shirt",
    brand: "Helen's Brand",
    price: 11,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/levender-hoodie.png",
    name: "Levender Hoodie",
    brand: "Nike's Brand",
    price: 119,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/leaves-pattern.png",
    name: "Leaves Pateter Shirt",
    brand: "Paypal's Brand",
    price: 77,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/graphic-top.png",
    name: "White Graphic Top",
    brand: "Woden's Brand ",
    price: 123,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/black-shorts.png",
    name: "Black Shirts ",
    brand: "MM's  Brand",
    price: 37,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/gray-sweatshirt.png",
    name: "Gray Sweatshirt",
    brand: "Priya's Brand",
    price: 78,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/yellow-sweatshirt.png",
    name: "Yellow Sweatshirt",
    brand: "Woden's Brand",
    price: 29,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/flower-pattern.png",
    name: "Flower Pattern Top",
    brand: "MM's Brand",
    price: 37,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/graphic-top2.png",
    name: "I don't graphic T-Shirt",
    brand: "Nisaragi's Brand",
    price: 73,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/blue-flower-pattern.png",
    name: "Blue Flower Sweatshirt",
    brand: "Mellon's Brand",
    price: 29,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "women",
    image: "/items/women/black-sweatshirt.jpg",
    name: "Line Pattern Hoodie",
    brand: "AS's Brand",
    price: 37,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
];

export const MenClothing: Item[] = [
  {
    category: "men",
    image: "/items/men/dgreen-tshirt.png",
    name: "Dark Green Sweatshirt",
    brand: "Roboto's Brand",
    price: 127,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "men",
    image: "/items/men/plain-tshirt.png",
    name: "Plain White T-Shirt",
    brand: "Jhavi's Brand",
    price: 123,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "men",
    image: "/items/men/lumberjack-shirt.png",
    name: "Lumberjeck Shirt",
    brand: "HM's Brand",
    price: 99,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "men",
    image: "/items/men/blue-shirt.png",
    name: "Denim Blue Shirt",
    brand: "MOMO's Brand",
    price: 38,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
  {
    category: "men",
    image: "/items/men/urban-jacket.png",
    name: "Urban Jacket",
    brand: "Sagar's Brand",
    price: 79,
    isFavorite: false,
    details: {
      fabric: "Bio-washed Cotton",
      pattern: "Printed",
      fit: "Regular Fit",
      neck: "Round Neck",
      sleeve: "Half-Sleeves",
      style: "Casual Wear",
    },
  },
];

export const Clothing = [...WomenClothing, ...MenClothing];
